import Head from "next/head";
import Link from "next/link";
import { Link as NextUILink } from "@nextui-org/react";

import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Hello World</h1>
        <Link href="/">
          <NextUILink color="secondary">Go to Button</NextUILink>
        </Link>
      </main>
    </>
  );
}
